spring:
  datasource:
    url: jdbc:mysql://82.157.38.57:3306/snowy-pub?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: leiw
    password: 7249458wlSHA@
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /pages/
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8089